name: angular_app
description: A web app that uses AngularDart called Tour of Heroes.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  ngdart: ^7.1.0
  ngforms: ^4.1.1
  ngrouter: ^3.1.1
  stream_transform: ^2.1.0

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  ngtest: ^4.1.1
  # #docregion build-dependencies
  build_runner: ^2.2.0
  build_test: ^2.1.5
  build_web_compilers: ^3.2.4
  # #enddocregion build-dependencies
  test: ^1.21.0
  mockito: ^3.0.2
  ngpageloader: ^5.0.0
# #enddocregion dev_dependencies
